//! Lemon Squeezy Webhook Handler Module
//!
//! This module handles webhook events from Lemon Squeezy payment provider.
//! When a purchase is completed, Lemon Squeezy sends a webhook that triggers
//! license key generation and delivery.
//!
//! ## Webhook Flow
//! 1. User completes payment on Lemon Squeezy
//! 2. Lemon Squeezy sends webhook to our backend
//! 3. Backend validates webhook signature
//! 4. Backend generates signed license key using Ed25519
//! 5. Backend sends license key to user via email
//!
//! ## Security
//! - Webhook signatures are verified using Lemon Squeezy's signing secret (HMAC-SHA256)
//! - License keys are signed with our private key (Ed25519)
//! - Sensitive data is never logged
//!
//! ## Integration Architecture
//! ```text
//! Lemon Squeezy → Webhook → Backend (this module) → Generate Signed Key → Email User
//! ```
//!
//! The licensing engine remains fully controlled by Rust:
//! - Lemon Squeezy: Payment processing, VAT/tax, order confirmation, license delivery
//! - Rust: License verification, signature validation, feature gating, offline enforcement

use serde::{Deserialize, Serialize};
use sha2::Sha256;

// ============================================================================
// LEMON SQUEEZY WEBHOOK TYPES
// ============================================================================

/// Lemon Squeezy webhook event types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebhookEventType {
    OrderCreated,
    OrderPaid,
    OrderRefunded,
    LicenseKeyCreated,
    LicenseKeyActivated,
}

/// Lemon Squeezy webhook payload
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookPayload {
    /// Event type
    pub event: String,
    /// Event data
    pub data: WebhookData,
    /// Timestamp
    pub timestamp: Option<String>,
}

/// Webhook data structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookData {
    /// Unique identifier for this event
    pub id: String,
    /// Order attributes
    pub attributes: WebhookAttributes,
}

/// Webhook attributes
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookAttributes {
    /// Order status
    pub status: Option<String>,
    /// Customer email
    pub user_email: Option<String>,
    /// Customer name
    pub user_name: Option<String>,
    /// Product name
    pub product_name: Option<String>,
    /// Variant name (e.g., "Pro", "Founder")
    pub variant_name: Option<String>,
    /// Order total
    pub total: Option<f64>,
    /// Currency
    pub currency: Option<String>,
    /// License key (if already generated by Lemon Squeezy)
    pub license_key: Option<String>,
}

// ============================================================================
// WEBHOOK VERIFICATION
// ============================================================================

/// Lemon Squeezy webhook signing secret
/// This is used to verify that webhooks are genuinely from Lemon Squeezy
/// TODO: Replace with actual signing secret from Lemon Squeezy dashboard
pub const LEMON_SQUEEZY_SIGNING_SECRET: &str = "your_signing_secret_here";

/// Verify Lemon Squeezy webhook signature
///
/// Lemon Squeezy signs webhooks with an HMAC-SHA256 signature.
/// This function verifies that signature.
///
/// # Arguments
/// * `payload` - The raw request body as bytes
/// * `signature` - The X-Signature header value
/// * `secret` - Your Lemon Squeezy signing secret
///
/// # Returns
/// * `true` if signature is valid
/// * `false` if signature is invalid
pub fn verify_webhook_signature(payload: &[u8], signature: &str, secret: &str) -> bool {
    use hmac::{Hmac, Mac};
    type HmacSha256 = Hmac<Sha256>;

    // Create HMAC-SHA256 with signing secret
    let mut mac = match HmacSha256::new_from_slice(secret.as_bytes()) {
        Ok(m) => m,
        Err(_) => return false,
    };

    // Update with payload
    mac.update(payload);

    // Get result
    let result = mac.finalize();
    let computed_signature = hex::encode(result.into_bytes());

    // Compare signatures (constant-time comparison would be better)
    computed_signature == signature
}

// ============================================================================
// LICENSE GENERATION FROM WEBHOOK
// ============================================================================

/// Product tier mapping from Lemon Squeezy variant names
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProductTier {
    Pro,
    Founder,
}

impl ProductTier {
    /// Parse from Lemon Squeezy variant name
    pub fn from_variant_name(name: &str) -> Option<Self> {
        let name_lower = name.to_lowercase();
        if name_lower.contains("founder") {
            Some(ProductTier::Founder)
        } else if name_lower.contains("pro") {
            Some(ProductTier::Pro)
        } else {
            None
        }
    }

    /// Convert to license tier string
    pub fn to_license_tier(&self) -> &'static str {
        match self {
            ProductTier::Pro => "PRO",
            ProductTier::Founder => "FOUNDER",
        }
    }
}

/// Generate a unique license ID
/// Format: XXXX-XXXX (8 alphanumeric characters)
pub fn generate_license_id() -> String {
    use rand::Rng;
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let mut rng = rand::thread_rng();

    let part1: String = (0..4)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect();

    let part2: String = (0..4)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect();

    format!("{}-{}", part1, part2)
}

/// License generation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedLicense {
    /// The full license key (format: ZFC-TIER-CODE.SIGNED_DATA)
    pub license_key: String,
    /// The tier (PRO or FOUNDER)
    pub tier: String,
    /// Customer email
    pub customer_email: String,
    /// License ID
    pub license_id: String,
    /// Whether the license was cryptographically signed
    pub is_signed: bool,
}

/// Process a Lemon Squeezy webhook and generate a license key
///
/// This function:
/// 1. Parses the webhook payload
/// 2. Determines the product tier
/// 3. Generates a signed license key (if signing key available)
/// 4. Returns the license for email delivery
///
/// # Arguments
/// * `payload` - The verified webhook payload
///
/// # Returns
/// * `Some(GeneratedLicense)` if successful
/// * `None` if the webhook doesn't require license generation
pub fn process_webhook(payload: &WebhookPayload) -> Option<GeneratedLicense> {
    // Only process order_paid events
    if payload.event != "order_paid" && payload.event != "order_created" {
        return None;
    }

    // Check order status
    let status = payload.data.attributes.status.as_ref()?;
    if status != "paid" {
        return None;
    }

    // Get customer info
    let customer_email = payload.data.attributes.user_email.as_ref()?.clone();
    let _customer_name = payload.data.attributes.user_name.as_ref();

    // Determine product tier
    let variant_name = payload.data.attributes.variant_name.as_ref()?;
    let tier = ProductTier::from_variant_name(variant_name)?;

    // Generate license ID
    let license_id = generate_license_id();

    // Generate the license key with optional signing
    let (license_key, is_signed) = generate_signed_license_key(&tier, &license_id);

    Some(GeneratedLicense {
        license_key,
        tier: tier.to_license_tier().to_string(),
        customer_email,
        license_id,
        is_signed,
    })
}

/// Generate a signed license key
///
/// This function creates a license key in the format:
/// `ZFC-TIER-CODE.SIGNED_DATA`
///
/// Where SIGNED_DATA contains the base64-encoded signed license payload.
///
/// # Arguments
/// * `tier` - The product tier (Pro or Founder)
/// * `license_id` - The unique license identifier (XXXX-XXXX format)
///
/// # Returns
/// A tuple of (license_key, is_signed) where is_signed indicates whether
/// the key was cryptographically signed
fn generate_signed_license_key(tier: &ProductTier, license_id: &str) -> (String, bool) {
    // Generate the base key format
    let base_key = format!("ZFC-{}-{}", tier.to_license_tier(), license_id);

    // In production with signing feature enabled, sign the license
    #[cfg(feature = "signing")]
    {
        use crate::license_crypto::SignedLicense;
        use std::sync::LazyLock;
        use ed25519_dalek::SigningKey;

        // Create the license payload
        let payload = LicensePayload::new(tier.to_license_tier().to_string(), license_id.to_string());

        // The signing key would be loaded from secure storage
        // This is a placeholder - in production, load from environment or secure storage
        static SIGNING_KEY: LazyLock<Option<SigningKey>> = LazyLock::new(|| {
            // TODO: Load actual signing key from secure storage
            // For now, return None to use unsigned keys
            None
        });

        if let Some(signing_key) = SIGNING_KEY.as_ref() {
            let signed = SignedLicense::sign(payload, signing_key);
            let encoded = signed.encode();
            return (format!("{}.{}", base_key, encoded), true);
        }
    }

    // Without signing feature or signing key, return unsigned key
    (base_key, false)
}

// ============================================================================
// WEBHOOK RESPONSE
// ============================================================================

/// Response to send back to Lemon Squeezy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookResponse {
    /// Success status
    pub success: bool,
    /// Message
    pub message: String,
    /// License key (only included in development mode)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license_key: Option<String>,
}

impl WebhookResponse {
    /// Create a success response
    pub fn success(message: &str) -> Self {
        Self {
            success: true,
            message: message.to_string(),
            license_key: None,
        }
    }

    /// Create an error response
    pub fn error(message: &str) -> Self {
        Self {
            success: false,
            message: message.to_string(),
            license_key: None,
        }
    }

    /// Add license key to response (for development)
    pub fn with_license_key(mut self, key: &str) -> Self {
        self.license_key = Some(key.to_string());
        self
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_product_tier_from_variant() {
        assert_eq!(ProductTier::from_variant_name("Pro License"), Some(ProductTier::Pro));
        assert_eq!(ProductTier::from_variant_name("Founder Edition"), Some(ProductTier::Founder));
        assert_eq!(ProductTier::from_variant_name("PRO"), Some(ProductTier::Pro));
        assert_eq!(ProductTier::from_variant_name("FOUNDER"), Some(ProductTier::Founder));
        assert_eq!(ProductTier::from_variant_name("Unknown"), None);
    }

    #[test]
    fn test_generate_license_id() {
        let id = generate_license_id();
        assert_eq!(id.len(), 9); // XXXX-XXXX
        assert!(id.contains('-'));
    }

    #[test]
    fn test_webhook_response() {
        let success = WebhookResponse::success("License generated");
        assert!(success.success);

        let error = WebhookResponse::error("Invalid signature");
        assert!(!error.success);
    }

    #[test]
    fn test_process_webhook() {
        let payload = WebhookPayload {
            event: "order_paid".to_string(),
            data: WebhookData {
                id: "test-123".to_string(),
                attributes: WebhookAttributes {
                    status: Some("paid".to_string()),
                    user_email: Some("test@example.com".to_string()),
                    user_name: Some("Test User".to_string()),
                    product_name: Some("Zetta Focus Console".to_string()),
                    variant_name: Some("Pro License".to_string()),
                    total: Some(29.0),
                    currency: Some("USD".to_string()),
                    license_key: None,
                },
            },
            timestamp: Some("2024-01-01T00:00:00Z".to_string()),
        };

        let result = process_webhook(&payload);
        assert!(result.is_some());

        let license = result.unwrap();
        assert_eq!(license.tier, "PRO");
        assert_eq!(license.customer_email, "test@example.com");
        assert!(license.license_key.starts_with("ZFC-PRO-"));
        // Without signing feature, is_signed should be false
        assert!(!license.is_signed);
    }

    #[test]
    fn test_generate_signed_license_key() {
        let tier = ProductTier::Pro;
        let license_id = "ABCD-1234";

        let (key, is_signed) = generate_signed_license_key(&tier, license_id);

        // Key should start with ZFC-PRO-
        assert!(key.starts_with("ZFC-PRO-ABCD-1234"));

        // Without signing feature, is_signed should be false
        assert!(!is_signed);
    }

    #[test]
    fn test_founder_license_generation() {
        let payload = WebhookPayload {
            event: "order_paid".to_string(),
            data: WebhookData {
                id: "test-456".to_string(),
                attributes: WebhookAttributes {
                    status: Some("paid".to_string()),
                    user_email: Some("founder@example.com".to_string()),
                    user_name: Some("Founder User".to_string()),
                    product_name: Some("Zetta Focus Console".to_string()),
                    variant_name: Some("Founder Edition".to_string()),
                    total: Some(19.0),
                    currency: Some("USD".to_string()),
                    license_key: None,
                },
            },
            timestamp: Some("2024-01-01T00:00:00Z".to_string()),
        };

        let result = process_webhook(&payload);
        assert!(result.is_some());

        let license = result.unwrap();
        assert_eq!(license.tier, "FOUNDER");
        assert!(license.license_key.starts_with("ZFC-FOUNDER-"));
    }
}
